### PR TITLE
Added the digamma function for real numbers

### PR DESCRIPTION
**Pull request by runarberg**

### CODE REVIEW

**Comment by IvanUkhov** [comment]
Thanks! I’ve looked at the thesis. I have three questions. First, why don’t you want to specify the coefficients of the expansion as fractions? That is, `1/12`, `1/120`, `1/252`, `1/240`, and so on. In my opinion, it’ll be much cleaner and more obvious what those magic numbers are. Second, what do you think about comping `inv_x_e2` raised into an increasing power by progressively  multiplying by `inv_x_e2` instead of calling `powi` multiple times? That is, reuse `inv_x_e2^n` to compute `inv_x_e2^(n+1)` (like what you did with `inv_x` and `inv_x_e2`). Lastly, how does this algorithm compare with [ASA103](http://people.sc.fsu.edu/~jburkardt/c_src/asa103/asa103.c)? Thanks!


Regards,
Ivan

**Comment by runarberg** [comment]
1. Yes, definitely. The coefficients are actually `Bernoulli[2n] / 2n (for n = 1..8)`. Perhaps we should add that as a comment as well.
2. Yes, that is a good point. Perhaps it could be better to create a `eval_poly!` macro that does that for us, as to not clutter the logic of the algorithm with `let` statements.
3. It is essentially the same algorithm, [ASA103](http://people.sc.fsu.edu/%7Ejburkardt/c_src/asa103/asa103.html) checks for the input (perhaps we could do a `debug_assert!`) and for small values (I would have to study the benefits of that). They use fewer coefficients in their expansion (maybe that's the reason for them checking for small values). They also use a `while`-loop instead of a recursion. For valid inputs, this will at most be 8 iterations (9 for ASA103), so the cost of recursion is trivial.

**Comment by IvanUkhov** [comment]
Regards the second point, I actually was thinking about cluttering the logic with `let` statements) [Here](https://github.com/ready-steady/ode/blob/master/dopri/main.go#L370-373) is an illustration of what I meant. I just wanted to reduce the computation of, say, `a.powi(7)` and `a.powi(8)` to 7 multiplications in total instead of 6 + 7 multiplications in total. I assume that `powi(8)` does all the job of `powi(7)` plus some more. However, these are just my speculations; I have no idea how [llvm.powi.f64](https://github.com/rust-lang/rust/blob/38c943f7efc4ac76efc1611a702e903ff8ad67b2/src/librustc_trans/trans/intrinsic.rs#L44) works under the hood.


Regards,
Ivan

**Comment by runarberg** [comment]
I decided on using a macro that utilises Horners method. It is optimal for reusing already computed values.

I tried the algorithm on values close to zero, and it seems to do fine. I suppose ASA103 had to compensate for expanding on so few terms.

**Comment by IvanUkhov** [comment]
Thank you!

**Comment by runarberg** [comment]
Another thing though. I noticed that the algorithm works for negative values as well, but for large negative values it might become somewhat inefficient due to the (non-tail) recursion. There might be some room for improvements there.

**Pull request merged**
